# Generated by Django 5.2.16 on 2026-07-15 16:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('patients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConstanteVitale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tension_systolique', models.PositiveIntegerField(blank=True, null=True)),
                ('tension_diastolique', models.PositiveIntegerField(blank=True, null=True)),
                ('temperature', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('poids', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('glycemie', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('infirmier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='constantes_saisies', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='constantes', to='patients.patient')),
            ],
            options={
                'verbose_name': 'Constante vitale',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Consultation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('type', models.CharField(choices=[('consultation', 'Consultation'), ('hospitalisation', 'Hospitalisation'), ('chirurgie', 'Chirurgie'), ('urgence', 'Urgence')], default='consultation', max_length=20)),
                ('diagnostic', models.CharField(blank=True, max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('medecin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consultations', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultations', to='patients.patient')),
                ('structure', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.structuresante')),
            ],
            options={
                'verbose_name': 'Consultation',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Examen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categorie', models.CharField(choices=[('analyses', 'Analyses'), ('imagerie', 'Imagerie'), ('autres', 'Autres')], default='analyses', max_length=12)),
                ('type_examen', models.CharField(max_length=120)),
                ('laboratoire', models.CharField(blank=True, max_length=150)),
                ('date', models.DateField()),
                ('statut', models.CharField(choices=[('normal', 'Normal'), ('eleve', 'Élevé'), ('critique', 'Critique')], default='normal', max_length=10)),
                ('resultat_texte', models.TextField(blank=True)),
                ('commentaire_labo', models.TextField(blank=True)),
                ('fichier', models.FileField(blank=True, null=True, upload_to='examens/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('laborantin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='examens_uploades', to=settings.AUTH_USER_MODEL)),
                ('medecin_prescripteur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='examens_prescrits', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='examens', to='patients.patient')),
            ],
            options={
                'verbose_name': 'Examen',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Ordonnance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('statut', models.CharField(choices=[('active', 'Active'), ('terminee', 'Terminée'), ('dispensee', 'Dispensée')], default='active', max_length=12)),
                ('instructions', models.TextField(blank=True)),
                ('signature_electronique', models.CharField(blank=True, max_length=255)),
                ('alertes_interactions', models.JSONField(blank=True, default=list)),
                ('dispensee_le', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('consultation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordonnances', to='medical.consultation')),
                ('dispensee_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordonnances_dispensees', to=settings.AUTH_USER_MODEL)),
                ('medecin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordonnances', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordonnances', to='patients.patient')),
                ('structure', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.structuresante')),
            ],
            options={
                'verbose_name': 'Ordonnance',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Medicament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150)),
                ('dosage', models.CharField(blank=True, max_length=80)),
                ('frequence', models.CharField(blank=True, max_length=120)),
                ('duree_jours', models.PositiveIntegerField(blank=True, null=True)),
                ('ordonnance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medicaments', to='medical.ordonnance')),
            ],
        ),
    ]
