# Generated by Django 5.2.16 on 2026-07-17 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='photo',
            field=models.ImageField(blank=True, help_text="Photo d'identité (visage centré).", null=True, upload_to='users/photos/'),
        ),
    ]
