# Generated by Django 5.2.16 on 2026-07-15 16:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DodoCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_chiffre', models.TextField(unique=True)),
                ('cvv', models.CharField(blank=True, max_length=3)),
                ('statut', models.CharField(choices=[('active', 'Active'), ('revoquee', 'Révoquée (perte/vol)'), ('expiree', 'Expirée'), ('reemise', 'Réémise')], default='active', max_length=10)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_expiration', models.DateField()),
                ('revoquee_le', models.DateTimeField(blank=True, null=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dodocards', to='patients.patient')),
                ('revoquee_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dodocards_revoquees', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'DodoCard',
                'verbose_name_plural': 'DodoCards',
                'ordering': ['-date_creation'],
            },
        ),
    ]
