# Generated by Django 5.2.16 on 2026-07-15 16:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('npi', models.CharField(help_text="Numéro Personnel d'Identification officiel, format BJ-XXXX-XXXXXXXX.", max_length=30, unique=True, verbose_name='NPI (ANIP)')),
                ('npi_verifie_anip', models.BooleanField(default=False, verbose_name='Vérifié ANIP')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('date_naissance', models.DateField(blank=True, null=True)),
                ('sexe', models.CharField(blank=True, choices=[('M', 'Masculin'), ('F', 'Féminin')], max_length=1)),
                ('groupe_sanguin', models.CharField(blank=True, choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=3)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='patients/photos/')),
                ('telephone', models.CharField(blank=True, max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('contact_urgence_nom', models.CharField(blank=True, max_length=120)),
                ('contact_urgence_lien', models.CharField(blank=True, max_length=60)),
                ('tel_urgence', models.CharField(blank=True, max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patient', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Patient',
                'verbose_name_plural': 'Patients',
                'ordering': ['nom', 'prenom'],
            },
        ),
        migrations.CreateModel(
            name='DossierMedical',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('antecedents', models.TextField(blank=True)),
                ('allergies', models.JSONField(blank=True, default=list)),
                ('maladies_chroniques', models.JSONField(blank=True, default=list)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dossier', to='patients.patient')),
            ],
            options={
                'verbose_name': 'Dossier médical',
                'verbose_name_plural': 'Dossiers médicaux',
            },
        ),
        migrations.CreateModel(
            name='Assurance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assureur', models.CharField(max_length=120)),
                ('num_police', models.CharField(max_length=80)),
                ('type_couverture', models.CharField(blank=True, max_length=120)),
                ('valide_du', models.DateField(blank=True, null=True)),
                ('valide_au', models.DateField(blank=True, null=True)),
                ('droits_valides', models.BooleanField(default=True)),
                ('garanties', models.JSONField(blank=True, default=list)),
                ('patient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='assurance', to='patients.patient')),
            ],
            options={
                'verbose_name': 'Assurance',
                'verbose_name_plural': 'Assurances',
            },
        ),
    ]
