# Generated by Django 5.2.16 on 2026-07-16 02:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_role'),
        ('cards', '0001_initial'),
        ('patients', '0002_patient_failed_pin_attempts_patient_pin_hash_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('approved', 'Approuvé'), ('denied', 'Refusé'), ('expired', 'Expiré'), ('emergency_bypass', 'Urgence (bypass)')], db_index=True, default='pending', max_length=20)),
                ('mode', models.CharField(choices=[('scan', 'Scan DodoCard'), ('search', 'Recherche / ouverture'), ('emergency', 'Mode urgence')], default='scan', max_length=20)),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('scope', models.CharField(default='full', max_length=40)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('grant_expires_at', models.DateTimeField(blank=True, null=True)),
                ('dodocard', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='access_requests', to='cards.dodocard')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_requests', to='patients.patient')),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_requests_made', to=settings.AUTH_USER_MODEL)),
                ('structure', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='access_requests', to='accounts.structuresante')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['patient', 'status'], name='patients_ac_patient_bc03be_idx'), models.Index(fields=['requester', 'status'], name='patients_ac_request_9db41e_idx')],
            },
        ),
    ]
