# Generated by Django 5.2.16 on 2026-07-17 14:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_role'),
        ('patients', '0003_accessrequest'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='accessrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'En attente'), ('approved', 'Approuvé'), ('denied', 'Refusé'), ('expired', 'Expiré'), ('emergency_bypass', 'Urgence (bypass)'), ('revoked', 'Révoqué')], db_index=True, default='pending', max_length=20),
        ),
        migrations.CreateModel(
            name='AccessBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lifted_at', models.DateTimeField(blank=True, null=True)),
                ('blocked_structure', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='access_blocks', to='accounts.structuresante')),
                ('blocked_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='access_blocks_received', to=settings.AUTH_USER_MODEL)),
                ('created_by_admin', models.ForeignKey(blank=True, help_text='Si renseigné : blocage forcé par un admin.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='access_blocks_forced', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_blocks', to='patients.patient')),
            ],
            options={
                'verbose_name': "Blocage d'accès",
                'verbose_name_plural': "Blocages d'accès",
                'ordering': ['-created_at'],
                'constraints': [models.CheckConstraint(condition=models.Q(('blocked_user__isnull', False), ('blocked_structure__isnull', False), _connector='OR'), name='accessblock_target_required')],
            },
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('debut', models.DateTimeField()),
                ('fin', models.DateTimeField(blank=True, null=True)),
                ('motif', models.CharField(blank=True, max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('statut', models.CharField(choices=[('planifie', 'Planifié'), ('confirme', 'Confirmé'), ('annule', 'Annulé'), ('termine', 'Terminé'), ('absent', 'Absent')], db_index=True, default='planifie', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments_created', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='patients.patient')),
                ('professionnel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments', to=settings.AUTH_USER_MODEL)),
                ('structure', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments', to='accounts.structuresante')),
            ],
            options={
                'verbose_name': 'Rendez-vous',
                'verbose_name_plural': 'Rendez-vous',
                'ordering': ['debut'],
                'indexes': [models.Index(fields=['patient', 'debut'], name='patients_ap_patient_adf77c_idx'), models.Index(fields=['professionnel', 'debut'], name='patients_ap_profess_36a0fb_idx'), models.Index(fields=['structure', 'debut'], name='patients_ap_structu_280034_idx')],
            },
        ),
    ]
