# Generated by Django 5.2.16 on 2026-07-22 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0006_patient_security_flags'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='adresse_commune',
            field=models.CharField(blank=True, max_length=120, verbose_name='Commune'),
        ),
        migrations.AddField(
            model_name='patient',
            name='adresse_quartier',
            field=models.CharField(blank=True, max_length=120, verbose_name='Quartier'),
        ),
        migrations.AddField(
            model_name='patient',
            name='lieu_naissance',
            field=models.CharField(blank=True, max_length=120, verbose_name='Lieu de naissance'),
        ),
        migrations.AddField(
            model_name='patient',
            name='nom_mere',
            field=models.CharField(blank=True, max_length=120, verbose_name='Nom de la mère'),
        ),
        migrations.AddField(
            model_name='patient',
            name='nom_pere',
            field=models.CharField(blank=True, max_length=120, verbose_name='Nom du père'),
        ),
    ]
